'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useAuth} from './auth-provider';
import {api,money} from '@/lib/api';
import {Badge,Button,Field,Loading,Notice,PageTitle,Pagination,Panel,inputClass} from './admin/ui';

export default function AccountApp({segments=[]}) {
  const [section,reference]=segments;
  if(section==='orders')return reference?<CustomerOrder reference={reference}/>:<CustomerOrders/>;
  if(section==='addresses')return <Addresses/>;
  if(section==='profile')return <Profile/>;
  return <Overview/>;
}
function Overview(){const {user}=useAuth();const [message,setMessage]=useState('');return <><PageTitle title="A little space for you." description="Keep track of the pieces you love and the orders on their way."/>{!user.email_verified_at&&<Panel className="mb-6"><h2 className="mb-3 text-lg font-semibold tracking-tight">Verify your email address</h2><p className="text-sm leading-6 text-stone-500">Confirm your email to unlock product reviews and keep your account details up to date.</p><Button variant="secondary" onClick={async()=>{try{setMessage((await api('/auth/verification-notification',{method:'POST'})).message);}catch(e){setMessage(e.message);}}}>Send verification email</Button><div className="mt-4"><Notice>{message}</Notice></div></Panel>}<div className="grid gap-5 sm:grid-cols-2">{[['My orders','See what is on its way.','orders'],['Your wishlist','Keep the good ones close.','wishlist'],['Saved addresses','Make next time a little easier.','addresses'],['Profile & security','Your details, your way.','profile']].map(([title,text,url])=><Link href={`/account/${url}`} key={url}><Panel className="h-full transition hover:border-emerald-300"><h2 className="mb-3 text-xl font-semibold tracking-tight">{title} ↗</h2><p className="m-0 text-sm text-stone-500">{text}</p></Panel></Link>)}</div></>;}
function CustomerOrders(){const [data,setData]=useState(null);const [page,setPage]=useState(1);const [error,setError]=useState('');useEffect(()=>{api(`/me/orders?page=${page}`).then(setData).catch(e=>setError(e.message));},[page]);return <><PageTitle title="Your orders" description="All orders placed while signed in to your account."/><Notice error>{error}</Notice>{!data?<Loading/>:<Panel>{!data.data.length?<div className="py-12 text-center"><h2 className="text-xl font-semibold tracking-tight">Your first favorite is waiting.</h2><Link href="/shop" className="text-sm text-emerald-800 underline">Explore the collection →</Link></div>:data.data.map(order=><Link href={`/account/orders/${order.reference}`} key={order.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-stone-100 py-5"><div><strong className="text-sm">Order #{order.id}</strong><p className="m-0 text-sm text-stone-500">{new Date(order.created_at).toLocaleDateString()}</p></div><Badge>{order.status}</Badge><strong className="text-sm">{money(order.total)} →</strong></Link>)}<Pagination data={data} onPage={setPage}/></Panel>}</>;}
function CustomerOrder({reference}){const [order,setOrder]=useState(null);const [error,setError]=useState('');useEffect(()=>{api(`/me/orders/${reference}`).then(setOrder).catch(e=>setError(e.message));},[reference]);return <><PageTitle title={order?`Order #${order.id}`:'Your order'} description={reference}/><Notice error>{error}</Notice>{!order?<Loading/>:<Panel><div className="mb-6 flex flex-wrap gap-3"><Badge>{order.status}</Badge><Badge>{order.payment_status}</Badge></div>{order.items.map(item=><div className="flex justify-between gap-5 border-b border-stone-100 py-4" key={item.id}><div><strong className="text-sm font-medium">{item.name}</strong><p className="m-0 text-sm text-stone-500">{item.size} / {item.color} · Qty {item.quantity}</p></div><span>{money(item.quantity*item.price)}</span></div>)}<p className="mt-6 text-sm text-stone-600">Shipping {money(order.shipping)} · Discount {money(order.discount)}</p><p className="text-lg font-semibold text-stone-900">Total {money(order.total)}</p><p className="text-sm leading-7 text-stone-500">Deliver to {order.address.line1}, {order.address.city}, {order.address.postal_code}, {order.address.country}{order.tracking_number&&<><br/>Tracking: {order.tracking_number}</>}</p></Panel>}</>;}
function Addresses(){const [data,setData]=useState(null);const [edit,setEdit]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [remove,setRemove]=useState(null);useEffect(()=>{api('/me/addresses').then(setData).catch(e=>setError(e.message));},[]);async function save(event){event.preventDefault();setBusy(true);try{await api(`/me/addresses${edit.id?'/'+edit.id:''}`,{method:edit.id?'PUT':'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setData(await api('/me/addresses'));setEdit(null);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}return <><PageTitle title="Saved addresses" action={<Button onClick={()=>setEdit({country:'US'})}>+ Add address</Button>}/><Notice error>{error}</Notice>{edit?<Panel><form onSubmit={save} className="grid gap-5 sm:grid-cols-2" key={edit.id||'new'}>{[['label','Address label'],['name','Full name'],['phone','Phone number'],['line1','Street address'],['city','City'],['postal_code','ZIP / postal code'],['country','Country code']].map(([key,label])=><Field key={key} label={label}><input required name={key} className={inputClass} defaultValue={edit[key]||''} maxLength={key==='country'?2:key==='postal_code'?20:200}/></Field>)}<div className="flex items-end gap-3"><Button disabled={busy}>{busy?'Saving…':'Save address'}</Button><Button variant="secondary" type="button" onClick={()=>setEdit(null)}>Cancel</Button></div></form></Panel>:!data?<Loading/>:<div className="grid gap-5 sm:grid-cols-2">{!data.length&&<Panel><p className="m-0 text-sm text-stone-500">No addresses saved yet.</p></Panel>}{data.map(address=><Panel key={address.id}><h2 className="mb-3 text-lg font-semibold tracking-tight">{address.label}</h2><p className="text-sm leading-7 text-stone-500">{address.name}<br/>{address.line1}<br/>{address.city}, {address.postal_code}<br/>{address.country} · {address.phone}</p><div className="flex gap-4"><Button variant="secondary" onClick={()=>setEdit(address)}>Edit</Button><button className="text-sm text-red-700" onClick={()=>setRemove(address.id)}>Remove</button></div></Panel>)}</div>}{remove&&<Panel className="mt-5"><p className="text-sm">Remove this saved address?</p><div className="flex gap-3"><Button variant="danger" onClick={async()=>{try{await api(`/me/addresses/${remove}`,{method:'DELETE'});setData(data.filter(a=>a.id!==remove));setRemove(null);}catch(e){setError(e.message);}}}>Remove address</Button><Button variant="secondary" onClick={()=>setRemove(null)}>Keep address</Button></div></Panel>}</>;}
function Profile(){const {user,setUser}=useAuth();const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function save(event,password=false){event.preventDefault();const form=event.currentTarget;setBusy(true);setError('');setMessage('');try{const result=await api(password?'/me/password':'/me',{method:password?'PUT':'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(form)))});if(password){form.reset();setMessage(result.message);}else{setUser(result);setMessage('Your profile has been updated.');}}catch(e){setError(e.message);}finally{setBusy(false);}}return <><PageTitle title="Profile & security" description="Keep your details current and your account secure."/><Notice error>{error}</Notice><Notice>{message}</Notice><div className="mt-5 space-y-6"><Panel><h2 className="mb-5 text-lg font-semibold tracking-tight">Your details</h2><form onSubmit={save} className="space-y-5"><Field label="Full name"><input className={inputClass} name="name" required defaultValue={user.name}/></Field><Field label="Email address"><input type="email" className={inputClass} name="email" required defaultValue={user.email}/></Field><Field label="Current password"><input type="password" className={inputClass} name="current_password" required autoComplete="current-password"/></Field><Button disabled={busy}>Save profile</Button></form></Panel><Panel><h2 className="mb-5 text-lg font-semibold tracking-tight">Change password</h2><form onSubmit={event=>save(event,true)} className="space-y-5">{[['current_password','Current password'],['password','New password'],['password_confirmation','Confirm new password']].map(([key,label])=><Field label={label} key={key}><input type="password" className={inputClass} name={key} required minLength={key==='current_password'?1:12} autoComplete={key==='current_password'?'current-password':'new-password'}/></Field>)}<p className="text-sm text-stone-500">Use at least 12 characters, including letters and numbers.</p><Button disabled={busy}>Update password</Button></form></Panel></div></>;}
