'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {useAuth} from './auth-provider';
import {api} from '@/lib/api';
import {Button,Field,Notice,inputClass} from './admin/ui';
export default function AuthForm({mode='login',admin=false,token='',email=''}) {
  const {login,logout}=useAuth();const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const titles={login:admin?'Welcome to your workspace.':'Good to see you again.',register:'Make yourself at home.','forgot-password':'Forgot your password?','reset-password':'A fresh start.'};
  async function submit(event){event.preventDefault();setBusy(true);setError('');setMessage('');const data=Object.fromEntries(new FormData(event.currentTarget));if(data.remember)data.remember=true;
    try {
      if(['login','register'].includes(mode)){const user=await login(data,mode==='register');if(admin&&user.role!=='admin'){await logout();throw new Error('This account does not have administrator access.');}router.replace(admin?'/admin':'/account');}
      else {const result=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify({...data,token})});setMessage(result.message);}
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  return <div className={`flex min-h-[75vh] items-center justify-center px-5 py-14 ${admin?'min-h-screen bg-stone-100':''}`}><div className="w-full max-w-md rounded-2xl border border-stone-200 bg-white p-7 shadow-sm sm:p-9"><Link href="/" className="text-3xl font-bold tracking-tighter text-emerald-950">mascot<span className="ml-1 text-sm">®</span></Link><p className="mb-3 mt-7 text-xs font-semibold uppercase tracking-[.2em] text-emerald-800">{admin?'Store administration':'Your everyday, together'}</p><h1 className="mb-3 text-3xl font-semibold leading-tight tracking-tight">{titles[mode]}</h1><p className="mb-6 text-sm leading-6 text-stone-500">{mode==='forgot-password'?'Enter your email and we will send a reset link.':admin?'Sign in to manage your store, catalog, and orders.':'Your orders, saved pieces, and details in one place.'}</p><form onSubmit={submit} className="flex flex-col gap-5"><Notice error>{error}</Notice><Notice>{message}</Notice>{mode==='register'&&<Field label="Full name"><input className={inputClass} name="name" autoComplete="name" required maxLength={120}/></Field>}<Field label="Email address"><input className={inputClass} type="email" name="email" autoComplete="email" defaultValue={email} required maxLength={200}/></Field>{mode!=='forgot-password'&&<Field label="Password" hint={mode!=='login'?'Use at least 12 characters, including letters and numbers.':undefined}><input className={inputClass} type="password" name="password" required minLength={mode==='login'?1:12} autoComplete={mode==='login'?'current-password':'new-password'}/></Field>}{['register','reset-password'].includes(mode)&&<Field label="Confirm password"><input className={inputClass} type="password" name="password_confirmation" required minLength={12} autoComplete="new-password"/></Field>}{mode==='login'&&<div className="flex items-center justify-between gap-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" name="remember" className="h-4 w-4 accent-emerald-800"/>Remember me</label><Link className="text-emerald-800 underline" href="/forgot-password">Forgot password?</Link></div>}<Button disabled={busy} type="submit">{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':mode==='forgot-password'?'Send reset link':'Reset password'}</Button></form><div className="mt-6 text-center text-sm text-stone-500">{mode==='login'&&!admin?<>New here? <Link className="font-semibold text-emerald-900" href="/register">Create an account</Link></>:<Link href={admin?'/':'/login'} className="font-semibold text-emerald-900">{admin?'Back to the storefront':'Back to sign in'}</Link>}</div></div></div>;
}
