'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import ProductCard from './product-card';
export default function Catalog({ category='', collection='', initialQuery='' }) {
  const [query,setQuery]=useState(initialQuery); const [sort,setSort]=useState('newest'); const [size,setSize]=useState(''); const [color,setColor]=useState(''); const [max,setMax]=useState(''); const [page,setPage]=useState(1);
  const [result,setResult]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [retry,setRetry]=useState(0);
  useEffect(()=>{ let active=true; const timer=setTimeout(()=>{
    setLoading(true); setError(''); const params=new URLSearchParams({sort,page:String(page)});
    Object.entries({category,collection,q:query,size,color,max_price:max}).forEach(([k,v])=>{if(v) params.set(k,v);});
    api(`/products?${params}`).then(data=>{if(active)setResult(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});
  },250); return ()=>{active=false;clearTimeout(timer);}; },[category,collection,query,sort,size,color,max,page,retry]);
  function change(setter,value){ setter(value);setPage(1); }
  return <><div className="catalog-toolbar"><input type="search" aria-label="Search products" placeholder="Search your next everyday favorite…" value={query} onChange={e=>change(setQuery,e.target.value)}/><select aria-label="Sort products" value={sort} onChange={e=>change(setSort,e.target.value)}><option value="newest">Newest arrivals</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div><div className="catalog-layout"><aside className="filters"><p className="eyebrow">REFINE YOUR EDIT</p><label>Size<select value={size} onChange={e=>change(setSize,e.target.value)}><option value="">All sizes</option>{['XS','S','M','L','XL','One size'].map(s=><option key={s}>{s}</option>)}</select></label><label>Color<select value={color} onChange={e=>change(setColor,e.target.value)}><option value="">All colors</option>{['Cloud','Oat','Sand','Olive','Indigo'].map(s=><option key={s}>{s}</option>)}</select></label><label>Price<select value={max} onChange={e=>change(setMax,e.target.value)}><option value="">Any price</option><option value="5000">Under $50</option><option value="10000">Under $100</option><option value="15000">Under $150</option></select></label><button className="text-button" onClick={()=>{setSize('');setColor('');setMax('');setQuery('');setPage(1);}}>Clear filters</button></aside><div className="catalog-results" aria-live="polite">{error?<div className="empty"><h2>A little pause.</h2><p>{error}</p><button className="button" onClick={()=>setRetry(retry+1)}>Try again</button></div>:loading?<div className="product-grid">{[1,2,3,4,5,6].map(n=><div className="skeleton" key={n}/>)}</div>:<><p className="result-count">{result?.total || 0} considered pieces</p><div className="product-grid">{result?.data.map(p=><ProductCard product={p} key={p.id}/>)}</div>{!result?.data.length&&<div className="empty"><h2>Nothing here just yet.</h2><p>Try another search or clear your filters.</p></div>}{result?.last_page>1&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {page} of {result.last_page}</span><button disabled={page===result.last_page} onClick={()=>setPage(page+1)}>Next →</button></div>}</>}</div></div></>;
}
