'use client';
import Link from 'next/link';
import { useState } from 'react';
import { usePathname } from 'next/navigation';
import { useStore } from './store-provider';
import Icon from './icons';
import { api } from '@/lib/api';
export function Header() {
  const { cart, wishlist } = useStore(); const [open, setOpen] = useState(false); const pathname = usePathname();
  return <><div className="announcement">A little something for your everyday. <span>Free shipping on orders $150+</span><Link href="/shop">Discover the collection ↗</Link></div><header className="header"><button className="icon-button mobile-menu" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}><Icon name="menu"/></button><Link href="/" className="logo">mascot<span>®</span></Link><nav className={open ? 'nav open' : 'nav'} aria-label="Main navigation">{[['New arrivals','/shop'],['Women','/category/women'],['Men','/category/men'],['Essentials','/category/essentials'],['Our story','/about']].map(([label,url]) => <Link className={pathname === url ? 'active' : ''} key={url} href={url} onClick={() => setOpen(false)}>{label}</Link>)}</nav><div className="header-actions"><Link href="/search" aria-label="Search"><Icon name="search"/></Link><Link href="/account/wishlist" aria-label={`Wishlist, ${wishlist.length} items`}><Icon name="heart"/></Link><Link href="/cart" aria-label={`Shopping bag, ${cart.reduce((n,i)=>n+i.quantity,0)} items`} className="bag-link"><Icon name="bag"/><span>{cart.reduce((n,i)=>n+i.quantity,0)}</span></Link></div></header></>;
}
export function Newsletter() {
  const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); try { const result = await api('/newsletter',{method:'POST',body:JSON.stringify({email:new FormData(event.currentTarget).get('email')})}); setMessage(result.message); } catch(e) { setMessage(e.message); } finally { setBusy(false); } }
  return <section className="newsletter"><div><p className="eyebrow">GOOD THINGS, IN YOUR INBOX</p><h2>Be part of the everyday.</h2><p>New collections, little inspirations, and a little something just for you.</p></div><form onSubmit={submit}><div className="email-input"><input aria-label="Email address" name="email" type="email" placeholder="Your email address" required/><button aria-label="Subscribe" disabled={busy}><Icon name="arrow"/></button></div><small>By subscribing, you agree to our <Link href="/privacy">Privacy Policy</Link>.</small><p role="status">{message}</p></form></section>;
}
export function Footer() { return <footer><div className="footer-top"><div><Link href="/" className="logo">mascot<span>®</span></Link><p>Considered clothing.<br/>For a life well lived.</p></div><div><h4>Explore</h4><Link href="/shop">All clothing</Link><Link href="/collections/everyday-edit">The Everyday Edit</Link><Link href="/collections/slow-days">Slow days collection</Link></div><div><h4>Here to help</h4><Link href="/contact">Contact us</Link><Link href="/shipping">Shipping & delivery</Link><Link href="/returns">Returns & exchanges</Link><Link href="/size-guide">Size guide</Link><Link href="/faq">FAQs</Link></div><div><h4>A little about us</h4><Link href="/about">Our story</Link><Link href="/journal">The journal</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms & conditions</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Mascot. Made for the everyday.</span><span>United States · USD $</span></div></footer>; }
