import Link from 'next/link';
import { notFound } from 'next/navigation';
import Contact from '@/components/contact';
const pages={
  about:['A little more us.','We’re Mascot. We believe getting dressed should be one of the easy parts of your day.',['Our point of view','A wardrobe should work with your life. We bring together relaxed silhouettes, versatile colors, and considered details to make everyday dressing feel a little more natural.'],['Buy what you love. Wear it often.','Our collections are designed around pieces that work together, with room for your own personality. Fewer decisions. More possibilities.']],
  shipping:['Good things are on their way.','Simple shipping, from our door to yours.',['Standard delivery','We currently ship within the United States. Standard delivery takes an estimated 5–7 business days after processing. Shipping is $8, or complimentary on orders of $150 or more before discounts.'],['Your delivery','Please provide a complete address and a reachable phone number. Cash on delivery is the available payment method. Contact us with your order reference for delivery questions.']],
  returns:['Find your perfect fit.','Sometimes it’s not quite right. We understand.',['30-day returns','Contact us within 30 days of delivery with your order reference. Items must be unworn, unwashed, and have their original tags attached. Our team will provide return instructions before you send anything.'],['Refunds & exchanges','Once your return is received and inspected, our team will confirm the refund method for your cash-on-delivery purchase. Original shipping charges are excluded unless the item arrived faulty. Contact us to arrange a size exchange, subject to stock.']],
  privacy:['Your privacy matters.','A little clarity about your information.',['What we collect','We store the contact and delivery details you provide at checkout, your order items, newsletter subscriptions, and messages you send us. Your bag and favorites are stored in this browser.'],['How we use it','We use order details to fulfill purchases and respond to inquiries. Newsletter signup is optional. Contact us to request access, correction, deletion, or newsletter removal.'],['External services','Product images are served by Unsplash, which receives the network information needed to deliver them. We do not collect card details.']],
  terms:['The everyday details.','Terms for shopping with Mascot.',['Orders & pricing','Prices are in US dollars. Your final order total and shipping charges are shown before you place your order. Orders are subject to stock availability and confirmation. Payment is due on delivery.'],['Product information','We aim to show accurate descriptions and images. Display colors may differ from the garment. Refer to your garment care label and the size guide.'],['Getting help','Contact us with any questions about an order. Our shipping and return policies form part of these terms. These policies do not limit rights provided by applicable consumer law.']],
  journal:['Notes on the everyday.','A little inspiration for getting dressed, and living well.',['The art of an easy wardrobe','Start with the pieces you reach for most. A familiar shirt, a pair of trousers that fits just right, and a layer for when the air turns cool. Let your everyday routines guide your wardrobe.'],['Slow mornings, good layers','A soft knit over a cotton tee. Sleeves pushed up. An easy tote at the door. The best outfits often come from small, simple choices.']],
};
export async function generateMetadata({params}){const {slug}=await params;return {title:pages[slug]?.[0]||({'faq':'Frequently asked questions','size-guide':'Size guide','contact':'Contact us'}[slug])||'Mascot'};}
export default async function Page({params}){const {slug}=await params;
  if(slug==='contact')return <div className="info-page"><p className="eyebrow">WE’RE HERE FOR YOU</p><h1>Let’s talk.</h1><p>Questions about a piece, your order, or finding the right fit? Leave us a note.</p><Contact/></div>;
  if(slug==='size-guide')return <div className="info-page"><p className="eyebrow">A LITTLE HELP WITH THE FIT</p><h1>Find your size.</h1><p>General body measurements in inches. Measure around the fullest part of your chest and hips, and your natural waist. Our clothing has a relaxed fit; individual styles may vary.</p><div className="table-scroll"><table><thead><tr><th>Size</th><th>Chest</th><th>Waist</th><th>Hip</th></tr></thead><tbody>{[['XS','32–34','25–27','34–36'],['S','34–36','27–29','36–38'],['M','36–39','29–32','38–41'],['L','39–42','32–35','41–44'],['XL','42–45','35–38','44–47']].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div><p>Between sizes? Choose the larger size for a roomier fit. <Link href="/contact">Ask us for help →</Link></p></div>;
  if(slug==='faq')return <div className="info-page"><p className="eyebrow">A FEW HELPFUL ANSWERS</p><h1>Good questions.</h1>{[['Where do you ship?','We currently ship within the United States. Standard shipping is $8, or free on orders of $150+.'],['How can I pay?','Cash on delivery is available at checkout. You won’t be asked for card details.'],['Can I shop without an account?','Absolutely. Guest checkout is available, and your bag and favorites are saved in this browser.'],['How do I return an item?','Contact us within 30 days of delivery with your order reference. Items should be unworn with their original tags.'],['How do I view my order?','Save the confirmation link and open it in the same browser used at checkout. Contact us with the order reference if you need assistance.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>;
  const page=pages[slug];if(!page)notFound();return <div className="info-page"><p className="eyebrow">THE MASCOT WAY</p><h1>{page[0]}</h1><p className="page-intro">{page[1]}</p>{page.slice(2).map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}<Link className="underlined" href={slug==='about'?'/shop':'/contact'}>{slug==='about'?'Discover your everyday →':'Get in touch →'}</Link></div>;
}
