'use client';
import {useState} from 'react';
import {api} from '@/lib/api';
import StoreImage from '@/components/store-image';
import {Button,Notice,Pagination} from './ui';
export default function MediaField({value,onChange,multiple=false}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [library,setLibrary]=useState(null);const [open,setOpen]=useState(false);
  const values=multiple?(value||[]):value?[value]:[];
  async function upload(files){setBusy(true);setError('');const uploaded=[];try{for(const file of [...files].slice(0,multiple?12-values.length:1)){if(file.size>2*1024*1024)throw new Error('Each photo must be 2 MB or smaller.');const form=new FormData();form.append('image',file);const result=await api('/admin/media/upload',{method:'POST',body:form});uploaded.push(result.url);}onChange(multiple?[...new Set([...values,...uploaded])]:uploaded[0]||value);}catch(e){if(uploaded.length)onChange(multiple?[...values,...uploaded]:uploaded[0]);setError(e.message);}finally{setBusy(false);}}
  async function browse(page=1){setOpen(true);try{setLibrary(await api(`/admin/media?page=${page}`));}catch(e){setError(e.message);}}
  return <div className="space-y-3"><div className="flex flex-wrap gap-3">{values.map((url,i)=><div key={url+i} className="relative h-32 w-28 overflow-hidden rounded-lg border border-stone-200 bg-stone-100"><StoreImage src={url} alt={`Selected photo ${i+1}`} sizes="112px" className="h-full w-full object-cover"/><button type="button" aria-label={`Remove photo ${i+1}`} onClick={()=>onChange(multiple?values.filter((_,index)=>index!==i):'')} className="absolute right-1 top-1 flex h-7 w-7 items-center justify-center rounded-full bg-white text-lg shadow">×</button></div>)}</div><div className="rounded-lg border-2 border-dashed border-stone-200 bg-stone-50 p-5" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!busy)upload(event.dataTransfer.files);}}><span className="mb-3 block text-sm font-normal text-stone-500">Drop photos here, or choose a file. JPEG, PNG or WebP, up to 2 MB each.</span><div className="flex flex-wrap items-center gap-3"><input type="file" aria-label="Upload photo" accept="image/jpeg,image/png,image/webp" multiple={multiple} disabled={busy} onChange={event=>{upload(event.target.files);event.target.value='';}} className="max-w-full text-sm file:mr-3 file:rounded-md file:border-0 file:bg-emerald-900 file:px-3 file:py-2 file:text-sm file:font-medium file:text-white"/><Button type="button" variant="secondary" onClick={()=>browse()}>Media library</Button></div>{busy&&<p role="status" className="mt-3 text-sm text-emerald-800">Uploading photos…</p>}</div><Notice error>{error}</Notice>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/40 p-4" role="dialog" aria-modal="true" aria-label="Choose from media library"><div className="max-h-[85vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="m-0 text-xl font-semibold tracking-tight">Choose a photo</h2><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Close</Button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{library?.data.map(item=><button type="button" key={item.id} className="overflow-hidden rounded-lg border border-stone-200 text-left hover:border-emerald-800" onClick={()=>{onChange(multiple?[...new Set([...values,item.url])].slice(0,12):item.url);setOpen(false);}}><StoreImage src={item.url} alt={item.original_name} sizes="160px" className="h-32 w-full object-cover"/><span className="block truncate p-2 text-xs">{item.original_name}</span></button>)}</div>{library&&!library.data.length&&<p className="py-10 text-center text-sm">Upload your first photo to get started.</p>}<Pagination data={library} onPage={browse}/></div></div>}</div>;
}
