const f=(key,label,type='text',extra={})=>({key,label,type,...extra});
export const resources={
  products:{title:'Products',description:'Create considered pieces and manage your storefront catalog.',columns:['name','price','status','category_id'],fields:[f('name','Product name'),f('slug','URL slug'),f('category_id','Category','select',{source:'categories'}),f('collection','Collection','select',{source:'collections',valueKey:'slug'}),f('description','Description','textarea'),f('price','Price (USD)','money'),f('compare_price','Compare-at price (USD)','money',{optional:true}),f('image','Cover photo','image'),f('images','Gallery photos','gallery'),f('badge','Product badge','text',{optional:true}),f('status','Visibility','select',{options:['draft','active','archived'],default:'draft'}),f('featured','Featured on homepage','checkbox')]},
  categories:{title:'Categories',description:'Organize your catalog with clear categories and cover photography.',columns:['name','slug','active'],fields:[f('name','Category name'),f('slug','URL slug'),f('description','Description','textarea'),f('image','Category photo','image',{optional:true}),f('active','Visible on storefront','checkbox',{default:true})]},
  collections:{title:'Collections',description:'Curate seasonal edits and stories for the storefront.',columns:['name','slug','active'],fields:[f('name','Collection name'),f('slug','URL slug'),f('description','Description','textarea'),f('image','Collection cover','image',{optional:true}),f('active','Visible on storefront','checkbox',{default:true})]},
  variants:{title:'Variants',description:'Manage sizes, colors, SKU codes, pricing, and variant photography.',columns:['sku','product_name','size','color','stock','active'],fields:[f('product_id','Product','select',{source:'products'}),f('sku','SKU'),f('size','Size'),f('color','Color name'),f('color_hex','Color swatch','color',{default:'#b9a88e'}),f('price','Price override (USD)','money',{optional:true,hint:'Leave blank to use the product price.'}),f('stock','Opening stock','number',{createOnly:true,default:0}),f('low_stock_threshold','Low stock alert threshold','number',{default:5}),f('image','Variant photo','image',{optional:true}),f('active','Available for purchase','checkbox',{default:true})]},
  coupons:{title:'Discounts',description:'Create promotions with minimum spend, expiry dates, and usage limits.',columns:['code','type','value','minimum','used','active'],fields:[f('code','Discount code'),f('type','Discount type','select',{options:['percent','fixed'],default:'percent'}),f('value','Discount value','number',{hint:'Percent: 1–100. Fixed: amount in cents (100 = $1).'}),f('minimum','Minimum order (USD)','money',{default:0}),f('usage_limit','Maximum uses','number',{optional:true}),f('expires_at','Expires at (store time)','datetime-local',{optional:true}),f('active','Promotion enabled','checkbox',{default:true})]},
  shipping:{title:'Shipping',description:'Set delivery destinations, costs, and free-shipping thresholds.',columns:['name','country','price','estimate','active'],fields:[f('name','Method name'),f('country','Country code','text',{default:'US',hint:'Two-letter uppercase country code, such as US or BD.'}),f('price','Shipping cost (USD)','money',{default:8}),f('free_threshold','Free shipping from (USD)','money',{optional:true}),f('estimate','Delivery estimate'),f('active','Available at checkout','checkbox',{default:true})]},
  pages:{title:'Pages',description:'Publish plain-text store pages. Existing storefront page slugs replace their default content.',columns:['title','slug','published'],fields:[f('title','Page title'),f('slug','URL slug'),f('body','Page content','textarea',{hint:'Use blank lines between paragraphs. HTML is displayed as text.'}),f('published','Published','checkbox',{default:true})]},
  customers:{title:'Customers & access',description:'Manage customer profiles, suspend access, or grant administrator permissions.',columns:['name','email','role','blocked'],fields:[f('name','Full name'),f('email','Email address','email'),f('role','Access role','select',{options:['customer','admin'],default:'customer',hint:'Administrators can manage all store operations.'}),f('password','New password','password',{optional:true,hint:'Required for new users: at least 12 characters with letters and numbers.'}),f('blocked','Suspend account access','checkbox')],noDelete:true},
  reviews:{title:'Reviews',description:'Moderate reviews submitted by verified customers after delivery.',columns:['product_name','customer_name','rating','comment','status'],fields:[f('status','Moderation status','select',{options:['pending','approved','rejected']})],noCreate:true},
  messages:{title:'Messages',description:'Read customer inquiries submitted through the contact page.',columns:['name','email','message','created_at'],readOnly:true},
  subscribers:{title:'Newsletter',description:'View subscribers and remove an email when a customer unsubscribes.',columns:['email','created_at'],readOnly:true},
  activity:{title:'Activity log',description:'A record of administrative changes, uploads, and stock adjustments.',columns:['action','resource','resource_id','user_id','created_at'],readOnly:true,noDelete:true},
};
