'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';
import {useAuth} from '@/components/auth-provider';
import {Button,Notice} from './ui';
const groups=[['Workspace',[['Overview',''],['Orders','orders'],['Payments','payments']]],['Catalog',[['Products','products'],['Variants','variants'],['Categories','categories'],['Collections','collections'],['Inventory','inventory'],['Media library','media']]],['Customers & growth',[['Customers & access','customers'],['Discounts','coupons'],['Reviews','reviews'],['Newsletter','subscribers']]],['Store operations',[['Shipping','shipping'],['Pages','pages'],['Messages','messages'],['Reports','reports'],['Activity log','activity'],['Settings','settings']]]];
export default function AdminShell({children}) {
  const {user,loading,logout}=useAuth();const pathname=usePathname();const router=useRouter();const [open,setOpen]=useState(false);const [error,setError]=useState('');
  const loginPage=pathname==='/admin/login';
  useEffect(()=>{if(!loading&&!user&&!loginPage)router.replace('/admin/login');},[loading,user,loginPage,router]);
  if(loginPage)return children;
  if(loading||!user)return <div className="flex min-h-screen items-center justify-center bg-stone-50 text-base text-stone-600">Opening your workspace…</div>;
  if(user.role!=='admin')return <div className="mx-auto max-w-xl p-10"><Notice error>Administrator access is required for this workspace.</Notice><Link href="/account" className="mt-5 inline-block text-sm underline">Back to your account</Link></div>;
  return <div className="min-h-screen bg-[#f6f7f5] font-sans text-sm text-stone-800"><aside className={`${open?'flex':'hidden'} fixed inset-y-0 left-0 z-40 w-64 flex-col border-r border-stone-200 bg-white lg:flex`}><div className="flex h-20 items-center justify-between border-b border-stone-100 px-6"><Link href="/admin" className="text-3xl font-bold tracking-tighter text-emerald-950">mascot<span className="ml-1 text-xs">®</span></Link><button aria-label="Close navigation" onClick={()=>setOpen(false)} className="p-2 text-xl lg:hidden">×</button></div><div className="flex-1 overflow-y-auto px-3 py-5">{groups.map(([label,links])=><div className="mb-5" key={label}><p className="mb-2 px-3 text-xs font-semibold uppercase tracking-wider text-stone-400">{label}</p>{links.map(([name,slug])=>{const href='/admin'+(slug?'/'+slug:'');const active=pathname===href||(slug&&pathname.startsWith(href+'/'));return <Link href={href} key={name} onClick={()=>setOpen(false)} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active?'bg-emerald-50 font-semibold text-emerald-950':'text-stone-600 hover:bg-stone-50'}`}><span className={`h-1.5 w-1.5 rounded-full ${active?'bg-emerald-800':'bg-stone-300'}`}/>{name}</Link>;})}</div>)}</div><Link href="/" className="border-t border-stone-100 px-6 py-5 text-sm font-medium text-stone-600">↗ View storefront</Link></aside>{open&&<button aria-label="Close menu overlay" className="fixed inset-0 z-30 bg-stone-950/30 lg:hidden" onClick={()=>setOpen(false)}/>}<div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-stone-200 bg-white/95 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button className="p-2 text-xl lg:hidden" aria-label="Open navigation" onClick={()=>setOpen(true)}>☰</button><div><span className="font-semibold">Store workspace</span><p className="m-0 text-xs text-stone-400">Manage the everyday.</p></div></div><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><strong className="text-sm font-semibold">{user.name}</strong><p className="m-0 text-xs text-stone-500">Administrator</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 font-semibold text-emerald-900">{user.name.slice(0,1).toUpperCase()}</span><Button variant="secondary" onClick={async()=>{try{await logout();router.replace('/admin/login');}catch(e){setError(e.message);}}}>Sign out</Button></div></header><main className="mx-auto max-w-[1500px] p-5 sm:p-8"><Notice error>{error}</Notice>{children}</main></div></div>;
}
