'use client';
import Link from 'next/link';
export const inputClass='w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-900 shadow-sm outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-700/15 disabled:bg-stone-100';
export function Button({children,variant='primary',className='',...props}) {return <button className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${variant==='danger'?'bg-red-700 text-white hover:bg-red-800':variant==='secondary'?'border border-stone-300 bg-white text-stone-800 hover:bg-stone-50':'bg-emerald-900 text-white hover:bg-emerald-800'} ${className}`} {...props}>{children}</button>;}
export function ButtonLink({children,href,...props}) {return <Link href={href} className="inline-flex min-h-10 items-center justify-center rounded-lg bg-emerald-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800" {...props}>{children}</Link>;}
export function Panel({children,className=''}){return <section className={`rounded-xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6 ${className}`}>{children}</section>;}
export function Field({label,hint,children}){return <label className="flex min-w-0 flex-col gap-2 text-sm font-medium text-stone-800">{label}{children}{hint&&<span className="text-sm font-normal leading-5 text-stone-500">{hint}</span>}</label>;}
export function Notice({children,error=false}){return children?<div role={error?'alert':'status'} className={`rounded-lg border px-4 py-3 text-sm leading-6 ${error?'border-red-200 bg-red-50 text-red-800':'border-emerald-200 bg-emerald-50 text-emerald-900'}`}>{children}</div>:null;}
export function Badge({children}){const positive=['active','approved','paid','delivered','admin','published'].includes(String(children));const negative=['archived','cancelled','rejected','blocked','refunded'].includes(String(children));return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${positive?'bg-emerald-50 text-emerald-800':negative?'bg-red-50 text-red-800':'bg-amber-50 text-amber-800'}`}>{children}</span>;}
export function PageTitle({title,description,action}){return <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="mb-2 text-2xl font-semibold tracking-tight text-stone-950 sm:text-3xl">{title}</h1>{description&&<p className="m-0 text-sm leading-6 text-stone-500">{description}</p>}</div>{action}</div>;}
export function Pagination({data,onPage}){return data&&data.last_page>1?<div className="mt-5 flex items-center justify-between gap-3 text-sm"><Button variant="secondary" disabled={data.current_page===1} onClick={()=>onPage(data.current_page-1)}>Previous</Button><span className="text-stone-500">Page {data.current_page} of {data.last_page}</span><Button variant="secondary" disabled={data.current_page===data.last_page} onClick={()=>onPage(data.current_page+1)}>Next</Button></div>:null;}
export function Loading(){return <div role="status" className="rounded-xl border border-stone-200 bg-white p-10 text-center text-sm text-stone-500">Loading your workspace…</div>;}
export function Empty({title='No records yet.',description='New records will appear here.'}){return <div className="px-6 py-14 text-center"><h3 className="mb-2 text-lg font-semibold text-stone-800">{title}</h3><p className="m-0 text-sm text-stone-500">{description}</p></div>;}
